---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: anand-ci-cd
    dev_namespace: anand-dev
    test_namespace: anand-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
